apiVersion: v1
kind: Pod
metadata:
  name: sayhi-custom1
  labels:
    pod-group.scheduling.sigs.k8s.io/name: say-hi-pod-group
    pod-group.scheduling.sigs.k8s.io/min-available: "2"
spec:
  schedulerName: lightweight-coscheduler
  containers:
    - name: app
      image: alpine
      command: ["/bin/echo", "hi"]
