apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: default
data:
  scheduler_config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    # clientConnection:
    #   kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
    profiles:
    - schedulerName: lightweight-coscheduler
      plugins:
        queueSort:
          enabled:
            - name: Coscheduling
          disabled:
            - name: "*"
        preFilter:
          enabled:
            - name: Coscheduling
        permit:
          enabled:
            - name: Coscheduling
        unreserve:
          enabled:
            - name: Coscheduling
